[package]
name = "rustysynth-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustysynth = "1.3.4"
sfml = "0.19.0"
